// Package verify performs read-only observations through Docker metadata,
// native files and public Hermes CLI commands.
package verify

import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/compose"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/launcher"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/process"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/qualification"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/target"
	"github.com/TrebuchetDynamics/hermes-repokit/internal/team"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Status string

const (
	Healthy      Status = "healthy"
	Degraded     Status = "degraded"
	PendingSetup Status = "pending-setup"
	Unsupported  Status = "unsupported"
	Unknown      Status = "unknown"
	Active       Status = "active"
	Inactive     Status = "inactive"
	Unqualified  Status = "unqualified"
	// Customized is a roster profile whose owner changed its identity. RepoKit
	// preserves it; it is not a fault, but RepoKit no longer vouches for it.
	Customized Status = "customized"
)

type Probe struct {
	Component string `json:"component"`
	Status    Status `json:"status"`
	Detail    string `json:"detail"`
}
type Runner interface {
	Run(context.Context, string, ...string) process.Result
}
type Runtime struct{ Status, Project, Workspace, Home string }

// InspectFormat selects only nonsecret Docker metadata, never Config.Env.
const InspectFormat = `{"status":{{json .State.Status}},"project":{{json (index .Config.Labels "com.docker.compose.project")}},"workspace":{{range .Mounts}}{{if eq .Destination "/workspace"}}{{json .Source}}{{end}}{{end}},"home":{{range .Mounts}}{{if eq .Destination "/opt/data"}}{{json .Source}}{{end}}{{end}}}`

func Inspect(ctx context.Context, id target.Identity, r Runner) []Probe {
	artifact := Probe{"compose", PendingSetup, "Compose file is absent"}
	if info, e := os.Lstat(id.Compose); e == nil {
		if info.Mode().IsRegular() {
			artifact = Probe{"compose", Unknown, "Compose exists; owner configuration is authoritative"}
		} else {
			artifact = Probe{"compose", Degraded, "Compose path is not a regular file"}
		}
	} else if !os.IsNotExist(e) {
		artifact = Probe{"compose", Unknown, "Compose metadata unavailable"}
	}
	runtime := Probe{"hermes", Unknown, "Docker runtime metadata unavailable"}
	result := process.Result{}
	dockerContext, contextErr := launcher.Context(id)
	if contextErr == nil {
		result = r.Run(ctx, "docker", "--context", dockerContext, "container", "inspect", "--format", InspectFormat, id.Container)
	} else {
		result.Err = contextErr
		runtime.Detail = "deployment Docker context unknown; launcher absent or owner-edited"
	}
	var state Runtime
	if result.Err == nil && !result.Truncated && json.Unmarshal([]byte(result.Output), &state) == nil {
		runtime.Status = Degraded
		runtime.Detail = "container identity or mounts do not match this repository"
		if state.Project == id.Project && state.Workspace == id.Root && state.Home == filepath.Join(id.Root, ".hermes") {
			if state.Status == "running" {
				runtime.Status = Healthy
				runtime.Detail = "container running with expected project and mounts; inference not probed"
			} else {
				runtime.Detail = "container is stopped; use ordinary Compose to start it"
			}
		}
	}
	config := Probe{"config", PendingSetup, "native configuration is absent"}
	if info, err := os.Lstat(filepath.Join(id.Root, ".hermes/config.yaml")); err == nil {
		config = Probe{"config", Degraded, "native configuration is not a nonempty regular file"}
		if info.Mode().IsRegular() && info.Size() > 0 {
			config = Probe{"config", Healthy, "native configuration exists; credentials and semantic contents not inspected"}
		}
	}
	launch := Probe{"launcher", Unknown, "standalone launcher absent, edited or unusable"}
	if info, err := os.Lstat(id.Launcher); err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0100 != 0 && contextErr == nil {
		launch = Probe{"launcher", Healthy, "recognized standalone launcher; native authentication not probed"}
	}
	// Compare only bounded public generated Compose, never credentials or receipt.
	if artifact.Status == Unknown {
		if o, ok := compose.DevelopmentSelected(id); ok {
			artifact = Probe{"compose", Healthy, "generated development Compose matches this repository"}
			if !compose.DevelopmentRecipeMatches(id, *o.Development) {
				artifact = Probe{"compose", Degraded, "development build recipe differs; owner state preserved"}
			}
			if o.SELinux.RelabelMode() != detectSELinux().RelabelMode() {
				artifact = Probe{"compose", Degraded, "repository bind mounts need SELinux relabel reconciliation; rerun install"}
			}
		}
	}
	if artifact.Status == Unknown {
		if _, ok := compose.DevelopmentInstallSelected(id); ok {
			artifact = Probe{"compose", Degraded, "generated by an older RepoKit; rerun install to upgrade (native state preserved)"}
		}
	}
	if artifact.Status == Unknown {
		expected, err := compose.Render(id, compose.Options{HermesImage: qualification.FoundationImage, UID: os.Getuid(), GID: os.Getgid(), SELinux: detectSELinux()})
		if err == nil && matchesCompose(id, expected) {
			artifact = Probe{"compose", Healthy, "generated Hermes-only Compose matches this repository"}
		}
	}
	board := Probe{"kanban", PendingSetup, "native board absent; run repokit install"}
	if info, err := os.Lstat(filepath.Join(id.Root, ".hermes/kanban.db")); err == nil {
		board = Probe{"kanban", Degraded, "native board is not a nonempty regular file"}
		if info.Mode().IsRegular() && info.Size() > 0 {
			board = Probe{"kanban", Healthy, "native board file exists; database not opened or validated"}
		}
	} else if !os.IsNotExist(err) {
		board = Probe{"kanban", Unknown, "native board metadata unavailable"}
	}
	if _, selected := compose.DevelopmentSelected(id); selected && runtime.Status == Healthy {
		if _, _, err := integrationRuntime(ctx, id, r); err != nil {
			runtime = Probe{"hermes", Degraded, "running container does not match selected development image or expected writable mounts; recreation may be pending"}
		}
	}
	probes := []Probe{artifact, runtime, config, launch, board, PythonImports(id)}
	if issues := target.Inspect(id, ""); len(issues) > 0 {
		probes = append(probes, Probe{"filesystem", Degraded, "unsafe or ambiguous repository/native state"})
	}
	return probes
}

func matchesCompose(id target.Identity, expected []byte) bool {
	root, err := os.OpenRoot(id.Root)
	if err != nil {
		return false
	}
	defer root.Close()
	f, err := root.Open(".hermes/compose.yaml")
	if err != nil {
		return false
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil || !info.Mode().IsRegular() {
		return false
	}
	data, err := io.ReadAll(io.LimitReader(f, 65537))
	return err == nil && len(data) <= 65536 && bytes.Equal(data, expected)
}

// Profiles checks generated public identities without invoking native commands.
// Healthy here describes scaffold files, never provider or integration acceptance.
func Profiles(id target.Identity) []Probe {
	var probes []Probe
	root, err := os.OpenRoot(filepath.Join(id.Root, ".hermes"))
	if err != nil {
		return []Probe{{"team", PendingSetup, "native home unavailable"}}
	}
	defer root.Close()
	for _, role := range team.ForRepository(id) {
		dir := "."
		if role.Name != "default" {
			dir = filepath.Join("profiles", role.Name)
		}
		probe := Probe{"profile:" + role.Name, Healthy, "generated role SOUL matches; description/configuration and runtime acceptance require native checks"}
		for _, file := range []string{"config.yaml", "profile.yaml", "SOUL.md"} {
			path := filepath.Join(dir, file)
			info, e := root.Lstat(path)
			if e != nil || !info.Mode().IsRegular() || info.Size() == 0 {
				probe.Status = PendingSetup
				probe.Detail = "profile files absent; run native default setup through RepoKit"
				break
			}
		}
		if probe.Status == Healthy {
			f, e := root.Open(filepath.Join(dir, "SOUL.md"))
			if e != nil {
				probe.Status = Unknown
			} else {
				soul, e := io.ReadAll(io.LimitReader(f, 65537))
				f.Close()
				if e == nil && string(soul) != role.Soul && managedHistory(role, string(soul)) {
					probe.Status = PendingSetup
					probe.Detail = "historical managed SOUL needs repository identity upgrade; run repokit setup"
				} else if e != nil {
					probe.Status = Degraded
					probe.Detail = "role SOUL unreadable"
				} else if string(soul) != role.Soul {
					probe.Status = Customized
					probe.Detail = "owner-customized SOUL preserved; RepoKit does not overwrite it (reset with install --reset-profile " + role.Name + ")"
				}
			}
		}
		probes = append(probes, probe)
	}
	return probes
}

// coreComponents must all be healthy for CORE_READY. Optional features (Docker
// acceptance) and descriptive rollups are deliberately excluded.
func coreComponent(name string) bool {
	switch name {
	case "compose", "hermes", "config", "launcher", "kanban", "filesystem", "git", "gateway",
		"kanban:dispatch", "kanban:notifications", "channels", "selinux", "access", "python-imports":
		return true
	}
	for _, prefix := range []string{"profile:", "development:", "channel:"} {
		if strings.HasPrefix(name, prefix) {
			return true
		}
	}
	return false
}

// Readiness summarizes observations into CORE_READY: whether RepoKit produced
// the repository team it promises. Hermes features RepoKit does not own, such
// as memory, are not reported.
// Healthy means configured, running AND behavior observed; core configured and
// running without observed reviewed work is Unqualified.
func Readiness(probes []Probe) []Probe {
	var failing, customized []string
	review := Unknown
	for _, p := range probes {
		if p.Status == Customized {
			customized = append(customized, strings.TrimPrefix(p.Component, "profile:"))
			continue
		}
		if coreComponent(p.Component) && p.Status != Healthy {
			failing = append(failing, p.Component)
		}
		if p.Component == "review:evidence" {
			review = p.Status
		}
	}
	sort.Strings(failing)
	core := Probe{"CORE_READY", Healthy, "Hermes, seven profiles, toolchain, Kanban, dispatch policy and gateway observed; same-card tester and reviewer acceptance observed"}
	if len(failing) > 0 {
		core = Probe{"CORE_READY", Degraded, "not ready: " + strings.Join(failing, ", ")}
	} else if review != Healthy {
		core = Probe{"CORE_READY", Unqualified, "configured and running; no automatic executor/tester/reviewer loop observed yet"}
	}
	// Owner customization is not a fault, but readiness names it: RepoKit's
	// role contract for those profiles rests on observed work, not on config.
	if len(customized) > 0 {
		sort.Strings(customized)
		core.Detail += "; owner-customized profiles: " + strings.Join(customized, ", ")
	}
	return []Probe{core}
}

// CoreUsable is verify's exit criterion: nothing core is broken or missing,
// even if the loop has not yet been exercised.
func CoreUsable(readiness []Probe) bool {
	return len(readiness) > 0 && readiness[0].Component == "CORE_READY" && readiness[0].Status != Degraded
}

// managedHistory reports whether soul is an earlier RepoKit-managed generation
// of role, which setup upgrades in place.
func managedHistory(role team.Role, soul string) bool {
	for _, s := range role.History() {
		if s == soul {
			return true
		}
	}
	return false
}
