"""Regression fixtures only: creates disposable native-like Git repositories."""
import os
from pathlib import Path
import subprocess
import sys
import tempfile
from unittest.mock import patch

scope = {"__name__": "fixture"}
exec(sys.argv[1], scope)
with tempfile.TemporaryDirectory() as temporary:
    root = Path(temporary)
    plugin = root / "plugins/nerve"
    plugin.mkdir(parents=True)
    env = {"PATH": "/usr/bin:/bin", "HOME": temporary, "GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": "/dev/null", "GIT_OPTIONAL_LOCKS": "0"}
    def git(*args):
        return subprocess.check_output(["git", "-C", str(plugin), *args], env=env, stderr=subprocess.DEVNULL).decode().strip()
    git("init", "-q")
    (plugin / "plugin.py").write_text("value = 1\n")
    (plugin / ".gitignore").write_text("ignored.py\n__pycache__/\n")
    git("add", ".")
    git("-c", "user.name=fixture", "-c", "user.email=fixture@example.invalid", "commit", "-qm", "fixture")
    revision = git("rev-parse", "HEAD")
    check = lambda: scope["verify_checkout"](plugin, root, revision)
    assert check(), "ordinary clean native checkout refused"
    # Native admission metadata and generated bytecode remain permissible.
    (plugin / ".hermes-catalog.json").write_text("{}")
    (plugin / "__pycache__").mkdir()
    (plugin / "__pycache__/plugin.cpython-311.pyc").write_bytes(b"fixture")
    assert check()
    # Index flags must never conceal modified tracked bytes.
    for flag in ("assume-unchanged", "skip-worktree"):
        git("update-index", "--" + flag, "plugin.py")
        (plugin / "plugin.py").write_text("value = 2\n")
        assert not check(), flag + " concealed edited source"
        (plugin / "plugin.py").write_text("value = 1\n")
        git("update-index", "--no-" + flag, "plugin.py")
    (plugin / "ignored.py").write_text("value = 3\n")
    assert not check(), "ignored Python source accepted"
    (plugin / "ignored.py").unlink()
    # Same-length content change triggers the old clean-filter execution path.
    config = plugin / ".git/config"
    original = config.read_text()
    marker = root / "filter-ran"
    git("config", "filter.sideeffect.clean", "touch " + str(marker) + "; cat")
    (plugin / ".gitattributes").write_text("plugin.py filter=sideeffect\n")
    (plugin / "plugin.py").write_text("value = 2\n")
    git("-c", "core.fsmonitor=false", "status", "--porcelain", "--untracked-files=all")
    assert marker.exists(), "fixture failed to reproduce original side effect"
    marker.unlink()
    with patch.object(scope["subprocess"], "run", side_effect=AssertionError("Git ran before raw config validation")):
        assert not check(), "filter configuration accepted"
    assert not marker.exists(), "verification executed a clean filter"
    config.write_text(original)
    (plugin / ".gitattributes").unlink()
    (plugin / "plugin.py").write_text("value = 1\n")
    assert check()
    # Includes and metadata/object indirections must be rejected before Git.
    for extension in ('[include]\npath = /outside/config\n', '[includeIf "gitdir:*"]\npath = /outside/config\n', '[extensions]\nworktreeConfig = true\n'):
        config.write_text(original + extension)
        with patch.object(scope["subprocess"], "run", side_effect=AssertionError("Git read configurable includes")):
            assert not check()
    config.write_text(original)
    for relative in ("objects/info/alternates", "commondir", "config.worktree"):
        path = plugin / ".git" / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("/outside\n")
        assert not check(), "metadata escape accepted"
        path.unlink()
    escaped = plugin / ".git/objects/escape"
    escaped.symlink_to(root, target_is_directory=True)
    assert not check(), "object directory symlink accepted"
    escaped.unlink()
    (plugin / "plugin.py").unlink()
    (plugin / "plugin.py").symlink_to(config)
    assert not check(), "tracked symlink accepted"
print("checkout safety fixtures passed")
